import{S as b,i as c}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const L="https://pixabay.com/api/",y=async({searchQuery:t,page:r=1,per_page:o=15})=>{const i=new URLSearchParams({key:"47362908-c1a65ba58d6ddf3afd8961379",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:o});try{const e=await fetch(`${L}?${i}`);if(!e.ok)throw new Error(e.statusText);return await e.json()}catch(e){console.error(e.message)}};let u;const w=({webformatURL:t,largeImageURL:r,tags:o,likes:i,views:e,comments:a,downloads:l})=>`<a href="${r}" class="gallery_item">
    <img src="${t}" alt="${o}" class="gallery__image" />
    <div class="info">
    <p class="info-item"><b>Likes</b> ${i}</p>
    <p class="info-item"><b>Views</b> ${e}</p>
    <p class="info-item"><b>Comments</b> ${a}</p>
    <p class="info-item"><b>Downloads</b> ${l}</p>
    </div>
    </a>`;function g(t){document.querySelector(".js-gallery").insertAdjacentHTML("beforeend",t.map(w).join("")),S()}function S(){u?u.refresh():u=new b(".js-gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}const q=document.querySelector(".js-search-form"),v=document.querySelector(".js-gallery"),p=document.querySelector(".loader"),s=document.querySelector(".js-load-more");let n=1;const m=15;let d="",f=0;q.addEventListener("submit",P);s.addEventListener("click",_);function h(t){t?p.classList.remove("hidden"):p.classList.add("hidden")}async function P(t){if(t.preventDefault(),d=t.target.elements.user_query.value.trim(),!d){s.classList.replace("load-more","hidden"),c.error({message:"Please write smth normal.",position:"topRight"});return}n=1,v.innerHTML="",s.classList.replace("load-more","hidden"),h(!0);try{const r=await y({searchQuery:d,page:n,per_page:m});if(r.total===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(r.hits),f=Math.ceil(r.totalHits/m),n<f&&s.classList.replace("hidden","load-more")}catch{c.error({message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{h(!1)}t.target.elements.user_query.value=""}async function _(){n++,s.disabled=!0;try{const t=await y({searchQuery:d,page:n,per_page:m});g(t.hits),n>=f&&(s.classList.replace("load-more","hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const o=document.querySelector(".gallery_item").getBoundingClientRect().height;window.scrollBy({left:0,top:o*2,behavior:"smooth"})}catch{c.error({message:"Failed to load more images. Please try again later.",position:"topRight"})}finally{s.disabled=!1}}
//# sourceMappingURL=index.js.map
