import{S as b,i as c}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const L="https://pixabay.com/api/",g=(t,r,a)=>{const i=new URLSearchParams({key:"47362908-c1a65ba58d6ddf3afd8961379",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:a});return fetch(`${L}?${i}`).then(e=>{if(!e.ok)throw new Error(e.statusText);return e.json()})};let u;const S=({webformatURL:t,largeImageURL:r,tags:a,likes:i,views:e,comments:o,downloads:n})=>`<a href="${r}" class="gallery_item">
    <img src="${t}" alt="${a}" class="gallery__image" />
    <div class="info">
    <p class="info-item"><b>Likes</b> ${i}</p>
    <p class="info-item"><b>Views</b> ${e}</p>
    <p class="info-item"><b>Comments</b> ${o}</p>
    <p class="info-item"><b>Downloads</b> ${n}</p>
    </div>
    </a>`;function y(t){document.querySelector(".js-gallery").insertAdjacentHTML("beforeend",t.map(S).join("")),q()}function q(){u?u.refresh():u=new b(".js-gallery a",{captions:!0,captionsData:"alt",captionDelay:250})}const w=document.querySelector(".js-search-form"),v=document.querySelector(".js-gallery"),p=document.querySelector(".loader"),s=document.querySelector(".js-load-more");let l=1;const m=15;let d="",f=0;w.addEventListener("submit",P);s.addEventListener("click",_);function h(t){t?p.classList.remove("hidden"):p.classList.add("hidden")}function P(t){if(t.preventDefault(),d=t.target.elements.user_query.value.trim(),!d){s.classList.replace("load-more","hidden"),c.error({message:"Please write smth normal.",position:"topRight"});return}l=1,v.innerHTML="",s.classList.replace("load-more","hidden"),h(!0),g(d,l,m).then(r=>{if(r.total===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(r.hits),f=Math.ceil(r.totalHits/m),l<f&&s.classList.replace("hidden","load-more")}).catch(r=>{console.log(r.message),c.error({message:"Failed to fetch images. Please try again later.",position:"topRight"})}).finally(()=>{h(!1)}),t.target.elements.user_query.value=""}async function _(){l++,s.disabled=!0;try{const t=await g(d,l,m);y(t.hits),l>=f&&(s.classList.replace("load-more","hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const a=document.querySelector(".gallery_item").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})}catch{c.error({message:"Failed to load more images. Please try again later.",position:"topRight"})}finally{s.disabled=!1}}
//# sourceMappingURL=index.js.map
